version: '3.8'

services:
  znaphub-api:
    build:
      context: .
      dockerfile: src/ZnapHub.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ZnapHubContext=Host=znaphub-db;Port=5432;Database=ZnapHub;Username=postgres;Password=postgrespw;Timeout=300;CommandTimeout=300
      - Minio__Endpoint=znaphub-minio:9000
      - Minio__AccessKey=minioadmin
      - Minio__SecretKey=minioadmin
      - Minio__Secure=false
      - Minio__Bucket=eventphotos
    depends_on:
      znaphub-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - znaphub-network

  znaphub-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ZnapHub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - znaphub-network
    
  znaphub-minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001" 
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    networks:
      - znaphub-network

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  znaphub-network:
    driver: bridge