apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: znaphub-secrets
  namespace: znaphub
spec:
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: znaphub
      secretsScope:
        envSlug: staging
        secretsPath: "/" 
  managedSecretReference:
    secretName: znaphub-secrets
    secretNamespace: znaphub
    creationPolicy: Orphan