apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: znaphub-ingress
  namespace: znaphub
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
        - api.staging.znaphub.com
        - auth.staging.znaphub.com
      secretName: znaphub-tls 
  rules:
    - host: api.staging.znaphub.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: znaphub-api
                port:
                  number: 8080
    - host: auth.staging.znaphub.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: znaphub-keycloak
                port:
                  number: 8080