<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ZnapHub.Domain\ZnapHub.Domain.csproj" />
      <ProjectReference Include="..\ZnapHub.Shared\ZnapHub.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Dtos\" />
    </ItemGroup>

</Project>
