name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      working-directory: ./src 
      run: dotnet restore ../ZnapHub.sln 
      
    - name: Build
      working-directory: ./src  
      run: dotnet build ../ZnapHub.sln --no-restore  
    
    - name: Test
      working-directory: ./src 
      run: dotnet test ../ZnapHub.sln --no-build --verbosity normal
